### ISSUE TITLE
flash-lone-windows is too strong

### ISSUE THREAD

**Issue by WuerfelDev** [fennerm/flashfocus#25]
I want my terminal windows to be transparent. Also lone windows should never flash. The problem is that a single terminal does not get the default-opacity. It gets transparent only when it was flashed once. 

![Screenshot from 2019-05-26 19-55-34](https://user-images.githubusercontent.com/12686819/58385433-a0503380-7ff0-11e9-982e-940f3ed41265.png)

My config is this:
```
flash-opacity: 0.8
default-opacity: 1
time: 500
simple: false
ntimepoints: 10
flash-on-focus: true
flash-lone-windows: 'never'
rules:
  - window-class: Brave-browser
    flash-on-focus: False
  - window-class: Gnome-terminal
    default-opacity: 0.8
    flash-opacity: 0.9
```

Basically when opening a lone window it should also check the rules or default-opacity too. Not sure which one of these is the problem

I'm running the latest pip release which seems to be 1.2.0
